[package]
name = "oxigres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
openssl = "0.10.55"
postgres = "0.19.5"
postgres-openssl = "0.5.0"
