name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Platform Toolchains
      run: rustup target add x86_64-unknown-linux-gnu aarch64-apple-darwin x86_64-pc-windows-gnu
    - name: Install Packages
      run: |
        sudo apt-get install -y pkg-config openssl libssl-dev 
        cargo clean 
        OPENSSL_INCLUDE_DIR="/usr/include/openssl" 
    - name: Build Linux
      run: |
        OPENSSL_LIB_DIR="/usr/lib/x86_64-unknown-linux-gnu"
        cargo build --lib --release --target x86_64-unknown-linux-gnu
    - name: Build MacOS
      run: |
        OPENSSL_LIB_DIR="/usr/lib/aarch64-apple-darwin"
        cargo build --lib --release --target aarch64-apple-darwin
    - name: Build Windows
      run: |
        OPENSSL_LIB_DIR="x86_64-pc-windows-gnu"
        cargo build --lib --release --target x86_64-pc-windows-gnu
    - name: Zip Artifacts
      run: zip -j target/release/liboxigres.zip target/release/liboxigres.so target/release/liboxigres.dll target/release/liboxigres.dylib
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: liboxigres.so
        path: target/release/liboxigres.zip
        if_no_files_found: error