name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Linux
      run: |
        cargo build --lib --release --target x86_64-unknown-linux-gnu
    - name: List Artifacts
      run: |
        ls -la /home/runner/work/oxigres-lib/oxigres-lib/target/release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: liboxigres.so
        path: /home/runner/work/oxigres-lib/oxigres-lib/target/release/liboxigres.so
        if_no_files_found: error